### ISSUE TITLE
EZ fix on Line 446 of nfa-liftfane-10-1.cfg

### ISSUE THREAD

**Issue by StrategyTron** [ChrisAdderley/NearFutureAeronautics#10]
Line 446 in the file 
     "/NearFutureAeronautics/Parts/Engine/LiftFans/nfa-liftfane-10-1.cfg"
Has an extra "}" that needs to be deleted, because everything that occurs after that line is not appearing in the game properly.
By just deleting it, it fixes all the problems related to things that occur below line 446.

EZ fix

**Comment by ChrisAdderley** [comment]
If it's so easy, why not submit a PR? ;)

**Comment by ChrisAdderley** [comment]
Released!
