### ISSUE TITLE
Name clash on CKAN

### ISSUE THREAD

**Issue by crane-denny** [ChrisAdderley/NearFutureAeronautics#18]
It looks like you have released this mod on CKAN but pointing to another mod of yours.
If I install Near Future Areonautics I get Cryo Engines installed instead.

**Comment by ChrisAdderley** [comment]
I don't think so - this mod is explicitly not supposed to be on CKAN. You might be seeing a package called `Cryogenic Engines - Near Future Aeronautics` which provides some optional integration content.
