### ISSUE TITLE
Model rebuild

### ISSUE THREAD

**Issue by rspeed** [ChrisAdderley/NearFutureAeronautics#20]
I saw on the KSP forums that you lost the source files for the models for this project. I've done some work reverse-engineering .mu files (most notably, getting Porkjet's engine revamp working again some time ago) and thought I might give this project a go. But I don't know what your process is for creating parts models, and a quick check of a couple repos didn't give any clues. If I managed to get everything rebuilt in Blender, would you be interested in getting this project going again?

**Comment by ChrisAdderley** [comment]
Sorry I never responded to this, honestly didn't see it. I never lost the models - I lost the intermediate configuration product between modeler and KSP. 

However, I think this is done now.
