### ISSUE TITLE
NFA medium lift fan not clickable in editor

### ISSUE THREAD

**Issue by oltsukoo** [ChrisAdderley/NearFutureAeronautics#24]
The medium sized lift fan in Near Future Aeronautics seems to be broken, it can't be clicked in the editor after placing it so I can't tweak the settings and can't even remove the part without Ctrl-Z'ing. This is on a vanilla KSP 1.10.1 installation with only NFA and no other mods. The large and small sized fans work as expected.

Demo GIF of me furiously clicking my mouse on the fan and nothing's happening: https://gfycat.com/concreteshamefulgoldeneye

Log file (the part where I place the fan and try to click it is at the end of the log just before I Alt-F4): [KSP.log](https://github.com/ChrisAdderley/NearFutureAeronautics/files/5320374/KSP.log)

**Comment by ChrisAdderley** [comment]
Fixed in last release.
