### ISSUE TITLE
update Localization

### ISSUE THREAD

**Issue by Aebestach** [ChrisAdderley/NearFutureAeronautics#28]
[zh-cn.txt](https://github.com/post-kerbin-mining-corporation/NearFutureAeronautics/files/8456652/zh-cn.txt)

**Comment by abel101126** [comment]
机翻不行吧

**Comment by Aebestach** [comment]
@abel101126 如果可以的话，可以进行修改上传的。

**Comment by abel101126** [comment]
在做了在做了
