### ISSUE TITLE
HOVR fans do not work in non-oxygenated atmospheres

### ISSUE THREAD

**Issue by StormCircuit** [ChrisAdderley/NearFutureAeronautics#31]
Take any HOVR fan and put it on Duna. It will flameout in electric mode.
![image](https://github.com/post-kerbin-mining-corporation/NearFutureAeronautics/assets/16582422/f8599b44-1f84-45fd-8a41-fa520ef0afd9)

**Comment by MehimoNemo** [comment]
I also encountered this issue

**Comment by MehimoNemo** [comment]
May be an easy fix though...

**Comment by ChrisAdderley** [comment]
The issue is that they don't get enough airflow on Duna (0.06 atm is very thin). They work fine in other atmospheres.
Latest release allowed them to work up to 0.03 atm, though the flow rate is quite poor at that level.
