### ISSUE TITLE
Nuclear engine center of mass is broken (COM outside of part)

### ISSUE THREAD

**Issue by june-dev-username** [ChrisAdderley/NearFutureAeronautics#32]
![Screenshot 2024-07-04 152845](https://github.com/post-kerbin-mining-corporation/NearFutureAeronautics/assets/140766131/515594cd-1dcc-4ddf-b7ff-124c0d8b0c51)

This applies both for the Fireflash nuclear engine and the project Eeloo engine

**Comment by guilimao** [comment]
A possible solution:  
Locate the two .cfg files in \GameData\NearFutureAeronautics\Parts\Engine\Atomic (corresponding to J-N500 and J-N160), and comment out "CoMOffset = 0.0, 3.5, 0.0". This will restore the center of mass of these two engines to a relatively reasonable position.

Before:
![before](https://github.com/user-attachments/assets/788c5d5e-19d2-4237-84cb-570927765ffd)

After:
![after](https://github.com/user-attachments/assets/ae8a2012-449d-4f09-a553-b5c69feffcc6)

**Comment by ChrisAdderley** [comment]
This is intended, in the same pattern as the stock jet engines, both of these engines only represent the combustion region of the nacelle and have an offset CM to reprsent the large mass of turbomachinery that would be in front of them.
