### ISSUE TITLE
missing a file

### ISSUE THREAD

**Issue by OzfurAtlas** [ChrisAdderley/NearFutureAeronautics#8]
VTOLControls.cfg is missing. It shoud be under: GameData\WildBlueIndustries\001KerbalActuators\Plugins/PluginData/KerbalActuators/
but it is not. Could you please upload a update with the cfg file to prevent errors. It may be causing crashes in KSP

**Comment by ChrisAdderley** [comment]
Talked with the dev and this shouldn't be an issue.
